language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
install:
  - pip install --use-mirrors nose coverage
script:
  - coverage erase
# Unit tests
  - coverage run setup.py test
# Integration test
  - coverage run virtualenv.py --distribute ./test-venv-01
# Another integration test, where we must download
  - cp -t bin virtualenv.py; coverage run bin/virtualenv.py --distribute ./test-venv-02
# How was our test coverage?
  - coverage report --show-missing
notifications:
  irc:
    channels: "irc.freenode.org#pip"
    on_success: change
    on_failure: change
