language: python

env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install:
  - "if [[ $TOXENV == 'py34' ]]; then .travis/py34.sh; fi"
  - pip install tox

script: tox

branches:
  only:
    - master
    - develop
    - 1.9.X
    - 1.10.X
    - 1.11.X

notifications:
  irc: "irc.freenode.org#pip"
