environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"
      TOXENV: "py27"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "64"
      TOXENV: "py27"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.6"
      PYTHON_ARCH: "32"
      TOXENV: "py33"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.6"
      PYTHON_ARCH: "64"
      TOXENV: "py33"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.2"
      PYTHON_ARCH: "32"
      TOXENV: "py34"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.2"
      PYTHON_ARCH: "64"
      TOXENV: "py34"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell .appveyor\\install.ps1"

build: off

test_script:
    - "%CMD_IN_ENV% %PYTHON%/Scripts/tox.exe"
